version: '3.7'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: orizhai
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: oridb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
