server:
  port: 9099

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: orizhai
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  threads:
    virtual:
      enabled: true

http:
  rest:
    max-total: 200
    default-max-per-route: 50
    connect-timeout: 5000
    read-timeout: 5000
    connection-request-timeout: 5000